export const API_ENDPOINTS = {
    users: {
        register: "/api/users/register",
        login: "/api/users/login",
        logout: "/api/users/logout",
        profile: "/api/users/profile",
        update: (userId: string) => `/api/users/${userId}`,
        getAll: "/api/users",
        getById: (id: string) => `/api/users/${id}`,
        delete: (id: string) => `/api/users/${id}`,
    },
    products: {
        create: "/api/products",
        getAll: "/api/products",
        getById: (id: string) => `/api/products/${id}`,
        update: (id: string) => `/api/products/${id}`,
        delete: (id: string) => `/api/products/${id}`,
        updateStockQuantity: (id: string) => `/api/products/${id}/stock-quantity`,
        getStockStatusAll: "/api/products/stock-status/all",
    },
    customers: {
        create: "/api/customers",
        getAll: "/api/customers",
        getById: (id: string) => `/api/customers/${id}`,
        update: (id: string) => `/api/customers/${id}`,
        delete: (id: string) => `/api/customers/${id}`,
    },
    offers: {
        getProducts: (search?: string) =>
            `/api/offers/products${search ? `?search=${encodeURIComponent(search)}` : ""}`,
        create: "/api/offers",
        getAll: "/api/offers",
        getById: (id: string) => `/api/offers/${id}`,
        getContractByUid: (uid: string) => `/api/offers/contract/${uid}`,
        updateStatus: (uid: string) => `/api/offers/uid/${uid}/status`,
        update: (id: string) => `/api/offers/${id}`,
        delete: (id: string) => `/api/offers/${id}`,
        getLastId: "/api/offers/last-id",
        sendOffer: (id: string) => `/api/offers/send-offer/${id}`,
        getHistory: (id: string) => `/api/offers/${id}/history`,
        sendContract: (id: string) => `/api/offers/send-contract/${id}`,
        getContractByOfferId: (offerId: string) => `/api/offers/contract-by-offer-id/${offerId}`,
        getByCustomerId: (customerId: string) => `/api/offers/customer/${customerId}`,
    },
    vehicles: {
        create: "/api/vehicles",
        getAll: "/api/vehicles",
        getById: (id: string) => `/api/vehicles/${id}`,
        update: (id: string) => `/api/vehicles/${id}`,
        delete: (id: string) => `/api/vehicles/${id}`,
        // Vehicle Parts endpoints
        getParts: (vehicleId: string) => `/api/vehicles/${vehicleId}/parts`,
        addPart: (vehicleId: string) => `/api/vehicles/${vehicleId}/parts`,
        updatePart: (vehicleId: string, partId: string) => `/api/vehicles/${vehicleId}/parts/${partId}`,
        deletePart: (vehicleId: string, partId: string) => `/api/vehicles/${vehicleId}/parts/${partId}`,
        getPartById: (vehicleId: string, partId: string) => `/api/vehicles/${vehicleId}/parts/${partId}`,
    },
    warehouses: {
        create: "/api/warehouses",
        getAll: "/api/warehouses",
        getById: (id: string) => `/api/warehouses/${id}`,
        update: (id: string) => `/api/warehouses/${id}`,
        delete: (id: string) => `/api/warehouses/${id}`,
    },
    operations: {
        create: "/api/operations",
        getAll: "/api/operations",
        getById: (id: string) => `/api/operations/${id}`,
        update: (id: string) => `/api/operations/${id}`,
        delete: (id: string) => `/api/operations/${id}`,
    },
    stations: {
        create: "/api/stations",
        getAll: "/api/stations",
        getById: (id: string) => `/api/stations/${id}`,
        update: (id: string) => `/api/stations/${id}`,
        delete: (id: string) => `/api/stations/${id}`,
    },
    productionPlans: {
        create: "/api/production-plans",
        getAll: "/api/production-plans",
        getById: (id: string) => `/api/production-plans/${id}`,
        update: (id: string) => `/api/production-plans/${id}`,
        delete: (id: string) => `/api/production-plans/${id}`,
        getByVehicle: (vehicleId: string) => `/api/production-plans/vehicle/${vehicleId}`,
    },
    dashboard: {
        summary: "/api/dashboard/summary",
        monthlyRevenue: "/api/dashboard/monthly-revenue",
        topProducts: "/api/dashboard/top-products",
        recentOffers: "/api/dashboard/recent-offers",
        customerActivity: "/api/dashboard/customer-activity",
        offerStatusDistribution: "/api/dashboard/offer-status-distribution",
    },
    payment: {
        create: "/api/payment",
        getByCustomerId: (customerId: string) => `/api/payment?customerId=${customerId}`,
        delete: (paymentId: string) => `/api/payment/${paymentId}`,
    },
} as const;
